### ISSUE TITLE
How I am doing my tests (without a Dockerfile)

### ISSUE THREAD

**Issue by paulatwilson** [stefanoeb/jest-action#4]
Not sure if this will help, but I have a simplified way of doing it (doesn't rely on docker at all)
```
name: Tests

on: [push]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      run: |
        npm install 
        npm test
```
