### ISSUE TITLE
Subdirectory?

### ISSUE THREAD

**Issue by Hyllesen** [stefanoeb/jest-action#8]
Sorry I'm new to github actions, but is it possible to run this action inside a subdirectory like /express or /client ?

**Comment by stefanoeb** [comment]
Yes, just pass the path you want in the `jestArgs` field:

```yml
name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.2
      with:
        jestArgs: client/
```
